### ISSUE TITLE
Recent flakiness of the bot?

### ISSUE THREAD

**Issue by ivirshup** [MeeseeksBox/MeeseeksDev#103]
Hey,

We've been noticing some flakiness of the bot on our projects:

* https://github.com/scverse/anndata/issues/1018

But also that there's a new bot name on some PRs, e.g. https://github.com/scverse/scanpy/pull/2235#issuecomment-1604242870

![image](https://github.com/MeeseeksBox/MeeseeksDev/assets/8238804/bd32fce6-4289-4289-9230-3244d64282fc)

![image](https://github.com/MeeseeksBox/MeeseeksDev/assets/8238804/8fa8ab77-23dc-4144-ba0a-f1055b12859f)

Any idea what's up/ if these things are connected? I don't think we've touched the CI on our end... @Carreau, are you going through with the changes you'd mentioned wanting to make at the scientific python summit (/ #99)?

cc: @flying-sheep

**Comment by Carreau** [comment]
The change of name is because we try to migrate the bot during a workshop but ran out of time, so rolled back. It might re-migrate during SciPy if the "new-name"/"new avatar" shows it's weird.

**Comment by ivirshup** [comment]
Ah, looks like we did sorta touch the CI.

Thanks for the quick feedback!

Should I be expecting the command (e.g. `@meeseeksdev backport to ...`) to change around then?

**Comment by Carreau** [comment]
> guess the bot should start ignoring text when it’s in `code blocks` …

Haha, yes, I'll try to have a proper parsing one day
