### ISSUE TITLE
Think of command case sensitivity.

### ISSUE THREAD

**Issue by Carreau** [MeeseeksBox/MeeseeksDev#17]
At least the first letter.

**Comment by blink1073** [comment]
The hello example in the readme should be lowercase methinks.

**Comment by Carreau** [comment]
It is now.

**Comment by Carreau** [comment]
it would not be hard to match lower case as well.

**Comment by blink1073** [comment]
👍 For insensitivity.

**Comment by Carreau** [comment]
Let's try to Tag (uppercase) and ClOse...

@meeseeksdev Tag bug
@meeseeksdev ClOsE

**Comment by blink1073** [comment]
@meeseeksdev HeLlO
