### ISSUE TITLE
Does Mr. MeeseeksDev like pandas?

### ISSUE THREAD

**Issue by TomAugspurger** [MeeseeksBox/MeeseeksDev#26]
If so, would he mind handling backports for us? :)

The pandas-people to add would be

- jreback
- jorisvandenbossche
- gfyoung
- TomAugspurger

Any other info you need? Our backports branches are named as `0.20.x` for the backports that should go from master to 0.20.1, 0.20.2, etc.

Thanks!

**Comment by Carreau** [comment]
Sure thing, done in 2c9b01cdcda9e257051b91fade43bd02051b226b

You can edit your milestones descriptions like [matplotlib does](https://github.com/matplotlib/matplotlib/milestones) to include a `on-merge: backport to 0.20.x` then head [there](https://github.com/integration/meeseeksdev/) and enable the integration.  The bot may need a restart after that; and yes I know I should ask for less permission, I still need to go through GitHub API docs and lower the permissions I request. 

I can also give you access to the heroku instance to see error logs if you desire.

**Comment by Carreau** [comment]
Did you had any chance to try ?

I've limited the permissions required quite a bit since you opened this issue.

**Comment by TomAugspurger** [comment]
Oh, sorry no. @jreback, I think you'll need to authorize it at https://github.com/integration/meeseeksdev/ since you're the admin. This should make backporting a bit easier.

**Comment by Carreau** [comment]
> Oh, sorry no. @jreback, I think you'll need to authorize it at integration/meeseeksdev since you're the admin. This should make backporting a bit easier.

No problem, just wanted to know if its working or not for you and if you need changes. I just got asked for another question and while I was taking care of it, wanted to check.

**Comment by Carreau** [comment]
I've lifted the restriction on whitelisted users, but still have an org whitelist. 

So you should not need me if you want to activate it.

cc'ing @stefanv who showed interest enabling the bot on scikit-image as well

**Comment by Carreau** [comment]
I've now implemented (in beta) the ability to backport without requiring push permissions. See https://github.com/MeeseeksBox/MeeseeksDev/issues/28

I'll switch the default mechanism after some testing, and then remove the request for push access.

**Comment by TomAugspurger** [comment]
Working now. Thanks!

**Comment by Carreau** [comment]
I've switched the default backport to a new version that should not ask for commit rights. Let me know if there is any issues. You can use `legacy_backport` if the new `backport` fails. Ping me if something's wrong. 

If the new backport mechanism works, I'll retire the old one and decrease necessary permissions.
