### ISSUE TITLE
Debug Matplotlib issues.

### ISSUE THREAD

**Issue by Carreau** [MeeseeksBox/MeeseeksDev#27]
@QuLogic you should be able to push changes and view logs via herokuCLI tool or using the browser based papertrail addon. 

things seem to be wrong in core.py ~ line 212:

```python
    print('[DEBUG] description:', description)
    print('[DEBUG] base ref:', is_pr['base']['ref'])
    if 'on-merge:' in description and is_pr['base']['ref'] == 'master':  #THIS <<<<<
        print('[DEBUG] on merge detected')
        for l in description.splitlines():
            print('[DEBUG] testing line...:{}'.format(l))
            if l.startswith('on-merge:'): ## OR THIS <<<<<<<
                todo = l[len('on-merge:'):].strip()
                print('After Merged in master; should:', todo)
                self.dispatch_on_mention('@meeseeksdev '+todo, payload, merged_by['login'])
```

If you push a commit on this repo it should automatically  be deployed.

**Comment by QuLogic** [comment]
OK, I'll take a look when we next merge something that needs a backport.

**Comment by QuLogic** [comment]
Actually, I think I see what it is based on the code above. The `on-merge:` must be at the beginning of the line, but we had the whole description all stuck together on one line. I've changed our milestones to put that on separate lines now.

**Comment by QuLogic** [comment]
OK, this is fixed downstream. I also added some messages in 55943c71ce232a0c32bffa2f5963c41b7f9cbea8 that will hopefully point out the problem in the future.

**Comment by Carreau** [comment]
great ! Thanks !
