### ISSUE TITLE
Have a way to tell bot to rebase its PR

### ISSUE THREAD

**Issue by pllim** [MeeseeksBox/MeeseeksDev#55]
Hello. Thanks for the awesome bot!

We ran into a situation where bot has a few backport PRs open but one of them fixes the CI for the rest. If we merge that one first, is there a way to tell the bot to *rebase* (not *pull*) its other PRs on the same repo to pick up that fix?

**Comment by Carreau** [comment]
Thanks !

I think that should be possible, not trivial as the bot is stateless by default, but we could do something along the line of:

- look for a `rebase-all` comment, 
- which branch is/was the PR the comment is on. 
- find all PRs on current repo that are by the same bot, 
- rebase and force-push them all (if conflict, post comment on relevant thread)

Feel free to send a PR (even with incomplete).

**Comment by pllim** [comment]
I was thinking of something simpler. Maybe a comment to trigger the bot as one would do with manual backport, but only this time, instead of opening a new backport PR, the bot rebases that existing PR. The bot can do some basic validation check on the author, milestone, and title to verify that it is indeed a backport PR to begin with.

This way, the maintainer has to trigger rebase per PR, which isn't unreasonable, given that not all backports might be affected.

**Comment by pllim** [comment]
Actually I found a workaround. I close the backport PR without merge, and then re-trigger the bot on the original PR. That works well enough for me. Thanks anyway!
