### ISSUE TITLE
MeeSeeksDev down?

### ISSUE THREAD

**Issue by adamgayoso** [MeeseeksBox/MeeseeksDev#59]
Radio silence now at scvi-tools

[example](https://github.com/scverse/scvi-tools/pull/1445)

**Comment by Carreau** [comment]
```
(b'{"message":"This installation has been suspended","documentation_url":"https://docs.github.com/rest/reference/apps#create-an-installation-access-token-for-an-app"}', 'https://api.github.com/app/installations/1139326/access_tokens')
```

from the logs it will take me some time to investigate

**Comment by Carreau** [comment]
There might be a couple more issues, that makes it crash during requests and not at startup, looking into it.

**Comment by Carreau** [comment]
meeseeksdev say hello

**Comment by Carreau** [comment]
Are you allright ?

**Comment by simonjayhawkins** [comment]
Thanks @Carreau seems OK for https://github.com/pandas-dev/pandas/pull/46404 now.

**Comment by blink1073** [comment]
Seems to be stable now.
