### ISSUE TITLE
Feature Request: Do not apply Still Needs Manual Backport label to backport PR

### ISSUE THREAD

**Issue by pllim** [MeeseeksBox/MeeseeksDev#93]
Workflow to trigger this:

1. Have two different backport labels applied, so when merged, a PR would be backported to two different release branches.
2. One of the release branch will have a failed backport, triggering the bot to apply "Still Needs Manual Backport".

Current behavior: If the failed backport happened first, the original PR will have "Still Needs Manual Backport" label applied. And then the backport to the other branch that succeeds after will also inherit this label.

Desired behavior: Bot is smart enough to not let the second backport to inherit this label.

Maybe not everyone will agree on this request, therefore I am opening an issue instead of attempting to patch it.

Example: https://github.com/astropy/astropy/pull/14104

**Comment by blink1073** [comment]
I have no objections

**Comment by pllim** [comment]
Thanks for the reply. Please see #94

**Comment by pllim** [comment]
I think we need to re-open this... Either #94 not really deployed or my patch failed and needs to be reverted.

https://github.com/astropy/astropy/pull/14107

**Comment by blink1073** [comment]
I verified the deploy commit matches the latest in `main`.

**Comment by pllim** [comment]
Oh no... something isn't working. 😿

**Comment by pllim** [comment]
I stared the the code I changed and I cannot find the bug. Similar label command using PyGitHub says my change is correct. I am stumped.

**Comment by pllim** [comment]
Oh wait, did I patch the wrong file? Should it be this instead?

https://github.com/MeeseeksBox/MeeseeksDev/blob/0698103f2fafb16a5bb0a48646240d4e68776886/meeseeksdev/meeseeksbox/commands.py#L729

If so, what is this actually used for?

https://github.com/MeeseeksBox/MeeseeksDev/blob/0698103f2fafb16a5bb0a48646240d4e68776886/meeseeksdev/commands.py#L53

**Comment by blink1073** [comment]
Ah, I believe the top level `commands.py` is not used anymore.   Thanks for the follow up fix!

**Comment by pllim** [comment]
Yay, I think it works now... https://github.com/astropy/astropy/pull/14125

**Comment by blink1073** [comment]
🎉
